language: node_js
node_js:
  - '10'

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install make git -qq
  - npm install -g yarn lerna

install:
  - lerna bootstrap

script:
  - lerna run build
  - yarn lint
  - yarn test

after_script:
  - "cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

cache: yarn
