language: node_js
node_js:
  - '8'

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install make git -qq
  - npm install -g yarn

install:
  - yarn install

script:
  - yarn lint
  - yarn test

cache: yarn
